//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SB004.Business.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class MailTemplates {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MailTemplates() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SB004.Business.Properties.MailTemplates", typeof(MailTemplates).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;html&gt;
        ///    &lt;head&gt;
        ///      &lt;title&gt;Reset your {{systemName}} password&lt;/title&gt;  
        ///    &lt;/head&gt;
        ///    &lt;body&gt;
        ///        &lt;h1&gt;Reset your {{systemName}} password&lt;/h1&gt;
        ///        &lt;p&gt;
        ///            Hi {{name}},
        ///        &lt;/p&gt;
        ///        &lt;p&gt;
        ///            To reset your {{systemName}} password, please click the following link:
        ///        &lt;/p&gt;
        ///        &lt;p&gt;
        ///            &lt;a target=&quot;_blank&quot; href=&quot;{{homePageUrl}}/{{userId}}/{{resetPassord}}?reset={{resetToken}}&quot;&gt;Reset my {{systemName}} password&lt;/a&gt;
        ///        &lt;/p&gt;
        ///        &lt;p&gt;
        ///          [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string forgotPassword_body {
            get {
                return ResourceManager.GetString("forgotPassword_body", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset your {{systemName}} password.
        /// </summary>
        internal static string forgotPassword_subject {
            get {
                return ResourceManager.GetString("forgotPassword_subject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;html&gt;
        ///    &lt;head&gt;
        ///      &lt;title&gt;Welcome to {{systemName}}&lt;/title&gt;  
        ///    &lt;/head&gt;
        ///    &lt;body&gt;
        ///        &lt;h1&gt;Welcome to {{systemName}}, {{name}}&lt;/h1&gt;
        ///        &lt;p&gt;
        ///            Welcome and thank you for registering with &lt;a href=&quot;{{homePageUrl}}&quot;&gt;{{systemName}}&lt;/a&gt;. 
        ///        &lt;/p&gt;
        ///        &lt;p&gt;
        ///            Your new account has now been created on &lt;a href=&quot;{{homePageUrl}}&quot;&gt;{{systemName}}&lt;/a&gt;
        ///            Everyone here at {{systemName}} hope you enjoy your experience :)
        ///        &lt;/p&gt;
        ///        
        ///        &lt;p&gt;Looking [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string welcome_body {
            get {
                return ResourceManager.GetString("welcome_body", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome to sb004, {{name}}.
        /// </summary>
        internal static string welcome_subject {
            get {
                return ResourceManager.GetString("welcome_subject", resourceCulture);
            }
        }
    }
}
